### PR TITLE
Add exception handling for add/delete tags; fix bugs

### LINKED ISSUE #98: Add exception handling for add/delete label commands

### PR DESCRIPTION
**Pull request by ryanguai**

### CODE REVIEW

File: src/main/java/seedu/address/logic/commands/tag/AddTagCommand.java [hunk 1]
```diff
@@ -46,25 +46,28 @@ public class AddTagCommand extends Command {
...
-     * @param index of the person in the filtered person list to edit
+     * @param contactIndex of the person in the filtered person list to edit
      * @param editPersonDescriptor details to edit the person with
      */
-    public AddTagCommand(Index index, EditPersonDescriptor editPersonDescriptor, EditTaskDescriptor editTaskDescriptor,
-        boolean addTagToContact, boolean addTagToTask) {
-        requireNonNull(index);
+    public AddTagCommand(Index contactIndex, Index taskIndex, EditPersonDescriptor editPersonDescriptor,
+        EditTaskDescriptor editTaskDescriptor, boolean addTagToContact, boolean addTagToTask) {
+        requireNonNull(contactIndex);
```
Comment (feliciagan) [inline src/main/java/seedu/address/logic/commands/tag/AddTagCommand.java:65]: should there be requireNonNull for taskIndex as well?

File: src/main/java/seedu/address/logic/parser/tag/DeleteTagCommandParser.java [hunk 2]
```diff
@@ -56,10 +58,10 @@ public DeleteTagCommand parse(String args) throws ParseException {
         parseTagsForEdit(argMultimap.getAllValues(PREFIX_TAG)).ifPresent(editTaskDescriptor::setTags);
 
         if (!editPersonDescriptor.isAnyFieldEdited()) {
```
Comment (feliciagan) [inline src/main/java/seedu/address/logic/parser/tag/DeleteTagCommandParser.java]: should it be (!editPersonDescriptor.isAnyFieldEdited() && !editTaskDescriptor.isAnyFieldEdited())?

File: src/main/java/seedu/address/logic/parser/tag/AddTagCommandParser.java [hunk 3]
```diff
@@ -37,15 +37,17 @@ public AddTagCommand parse(String args) throws ParseException {
...
+        Index contactIndex;
+        Index taskIndex;
 
         boolean addTagToContact = argMultimap.getValue(PREFIX_CONTACT).isPresent();
         boolean addTagToTask = argMultimap.getValue(PREFIX_TASK).isPresent();
 
         try {
-            index = ParserUtil.parseIndex(argMultimap.getPreamble());
+            contactIndex = ParserUtil.parseIndex(argMultimap.getValue(PREFIX_CONTACT).orElse("1"));
+            taskIndex = ParserUtil.parseIndex(argMultimap.getValue(PREFIX_TASK).orElse("1"));
```
Comment (feliciagan) [inline src/main/java/seedu/address/logic/parser/tag/AddTagCommandParser.java:48]: does this cause a bug when user input is index 1?

**Review by feliciagan — COMMENTED** [review]
Maybe update the UG to match the new command format

File: src/main/java/seedu/address/logic/parser/tag/AddTagCommandParser.java (hunk 3 above)
Comment (ryanguai) [reply src/main/java/seedu/address/logic/parser/tag/AddTagCommandParser.java:48]: The 1 is essentially a dummy value because there is a boolean addTagToContact and addTagToTask to check if there is a value present in the first place. If there is no value, the index stored is not used.

**Review by feliciagan — COMMENTED** [review]
LGTM
